export const GET_COUNTRIES = "GET_COUNTRIES";
export const ERROR_GET_COUNTRIES = "ERROR_GET_COUNTRIES";
export const GET_MORTALITY = "GET_MORTALITY";
export const ERROR_GET_MORTALITY = "ERROR_GET_MORTALITY";